<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LookupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehicle_types')->insert([
            ['type_name' => 'Car'],
            ['type_name' => 'Van'],
            ['type_name' => 'Bus'],
            ['type_name' => 'SUV'],
        ]);

        DB::table('vehicle_attributes')->insert([
            ['make' => 'Toyota', 'model' => 'Corolla'],
            ['make' => 'Toyota', 'model' => 'Camry'],
            ['make' => 'Honda', 'model' => 'Civic'],
            ['make' => 'Honda', 'model' => 'Accord'],
            ['make' => 'Ford', 'model' => 'F-150'],
            ['make' => 'Ford', 'model' => 'Mustang'],
            ['make' => 'Chevrolet', 'model' => 'Malibu'],
            ['make' => 'BMW', 'model' => '3 Series'],
            ['make' => 'Mercedes-Benz', 'model' => 'C-Class'],
            ['make' => 'Nissan', 'model' => 'Altima'],
            ['make' => 'Hyundai', 'model' => 'Elantra'],
            ['make' => 'Volkswagen', 'model' => 'Golf'],
            ['make' => 'Subaru', 'model' => 'Outback'],
        ]);

        DB::table('companies')->insert([
            ['name' => 'Explore Vacations', 'logo' => 'assets/logos/ev.png'],
            ['name' => 'SR Rent A Car', 'logo' => 'assets/logos/rentacar.png'],
            ['name' => 'Elite Rent A Car', 'logo' => 'assets/logos/ellite.png'],
        ]);

        DB::table('fuel_types')->insert([
            ['fuel_name' => 'Petrol'],
            ['fuel_name' => 'Diesel'],
            ['fuel_name' => 'Hybrid'],
            ['fuel_name' => 'Electric'],
        ]);

        DB::table('vehicle_categories')->insert([
            ['name' => "Mini Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Economy Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Standard Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Semi Executive Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Executive Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Luxury Cars", 'vehicle_type_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Mini SUVs", 'vehicle_type_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Large SUVs", 'vehicle_type_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Mini Van", 'vehicle_type_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Van", 'vehicle_type_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Luxury Coach", 'vehicle_type_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => "Super Luxury Coach", 'vehicle_type_id' => 3, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('transmissions')->insert([
            ['transmission_name' => 'Manual'],
            ['transmission_name' => 'Automatic'],
        ]);

        DB::table('ownership_types')->insert([
            ['ownership_name' => 'Company-owned'],
            ['ownership_name' => 'Leased'],
            ['ownership_name' => 'Rented'],
        ]);

        DB::table('defect_categories')->insert([
            ['name' => 'Service', 'description' => 'General vehicle maintenance and service tasks', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wheels & Tyres', 'description' => 'Issues related to tyres, rims, wheel alignment, and balancing', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brakes', 'description' => 'Problems with brake pads, discs, calipers, and overall braking system', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ABS', 'description' => 'Faults in Anti-lock Braking System and related sensors', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Suspension', 'description' => 'Suspension components, shock absorbers, and stability-related issues', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Differential', 'description' => 'Differential gears, axle, and related drivetrain issues', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine', 'description' => 'Engine performance, combustion, and internal mechanical issues', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Transmission', 'description' => 'Manual or automatic transmission, gearbox, and clutch faults', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Battery', 'description' => 'Battery health, charging issues, and electrical power supply', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cooling System', 'description' => 'Radiator, coolant, and engine cooling system problems', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'A/C System', 'description' => 'Air conditioning, heating, and climate control issues', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Light System', 'description' => 'Headlights, taillights, indicators, and other vehicle lighting faults', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Exterior', 'description' => 'Bodywork, paint, mirrors, doors, and exterior cosmetic issues', 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('faults')->insert([
            ['name' => 'BONET', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT BUMPER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR BUMPER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FENDER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FENDER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H QUARTER PANEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H QUARTER PANEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT INNER MUD GUARD', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT INNER MUD GUARD', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR INNER MUD GUARD', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR INNER MUD GUARD', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H SIDE MIRROR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H SIDE MIRROR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT THIRD MIRROR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR THIRD MIRROR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H WINKER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H WINKER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H SIDE MIRROR LENS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H SIDE MIRROR LENS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT DOOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT DOOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR DOOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR DOOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT DOOR HANDLE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT DOOR HANDLE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR DOOR HANDLE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR DOOR HANDLE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT DOOR VISOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT DOOR VISOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR DOOR VISOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR DOOR VISOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT WINDSCREEN', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR WINDSCREEN', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT WIPER BLADE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT WIPER BLADE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT DOOR SHUTTER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H DOOR SHUTTER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT DOOR CORNER GLASS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT DOOR GLASS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR DOOR CORNER GLASS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR DOOR CORNER GLASS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H SKIRTING', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H SKIRTING', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FOOTSTEP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FOOTSTEP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ROOF', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H ROOF RAILS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H ROOF RAILS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ANTENNA', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FISH TAIL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FUEL CAP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'DICKEY DOOR', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT GRILL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT NUMBER PLATE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR NUMBER PLATE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT VEHICLE BADGE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR VEHICLE BADGE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SIDE VEHICLE BADGE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT FOG LIGHT CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT FOG LIGHT CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT TYRE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT TYRE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR TYRE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR TYRE', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT WHEEL NUTS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT WHEEL NUTS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR WHEEL NUTS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR WHEEL NUTS', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT ALLOY WHEEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT ALLOY WHEEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR ALLOY WHEEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR ALLOY WHEEL', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT RIM CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT RIM CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR RIM CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR RIM CUP', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SILENCER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ENGINE UNDER COVER', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REVERSE CAMERA', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT CAMERA', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H SIDE MIRROR CAMERA', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H SIDE MIRROR CAMERA', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT SIGNAL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT SIGNAL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT FOG LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT FOG LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR TAIL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR TAIL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR SIGNAL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR SIGNAL LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR BUMPER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR BUMPER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REVERSE LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REVERSE LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FENDER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FENDER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR CENTER LIGHT', 'type' => 'exterior', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'LICENCE INSURANCE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FUEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'MILAGE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'METER BOARD', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'DASH BOARD', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT A/C VENTS', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR A/C VENTS', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'AUDIO & CAR DISPLAY', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'STEERING WHEEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'STEERING WHEEL MULTIFUNCTION BUTTONS', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SIGNAL LEVER', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'WIPER LEVER', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'DASH BOARD NOBS', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT CABIN', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CENTER CONSOLE CABIN', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'GEAR SHIFT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'HAND BRAKE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CLUTCH PADDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'BRAKE PADDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ACCELERATOR PADDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR VIEW MIRROR', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT INNER DOOR PANEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT INNER DOOR PANEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR INNER DOOR PANEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR INNER DOOR PANEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT INNER DOOR HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT INNER DOOR HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR INNER DOOR HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR INNER DOOR HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'DRIVER MAIN SHUTTER SWITCH', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT SHUTTER SWITCH', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR SHUTTER SWITCH', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR SHUTTER SWITCH', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SIDE MIRRORS FUNCTION SWITCH', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT SUN VISOR', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT SUN VISOR', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT HOOD HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT HOOD HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR HOOD HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR HOOD HANDLE', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'FRONT HOOD LIGHT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR HOOD LIGHT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SUNROOF SWITCH PANEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT SEAT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT SEAT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR SEAT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR SEAT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR CENTER SEAT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '01ST REAR ROW SEAT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '02ND REAR ROW SEAT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '03RD REAR ROW SEAT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '04TH REAR ROW SEAT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '05TH REAR ROW SEAT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT SEAT BELT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT SEAT BELT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR SEAT BELT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR SEAT BELT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CENTER SEAT BELT', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '01ST REAR ROW SEAT BELT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '02ND REAR ROW SEAT BELT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '03RD REAR ROW SEAT BELT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '04TH REAR ROW SEAT BELT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '05TH REAR ROW SEAT BELT (VAN)', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H FRONT CARPET', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H FRONT CARPET', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'R/H REAR CARPET', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'L/H REAR CARPET', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'SPARE WHEEL', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TOOLS', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'REAR BOOT COVER', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INTERIOR', 'type' => 'interior', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('issues')->insert([
            ['name' => 'Normal Service', 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Full Service', 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Front Trye (R/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Trye (L/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Trye (R/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Trye (L/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Alloy Wheel (R/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Alloy Wheel (L/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Trye (R/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Alloy Wheel (R/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Alloy Wheel (L/H)', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Valve', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wheel Balancing', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wheel Alignment', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Break Oil', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Break Oil Leak', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pads', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shoe', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Liner', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Disk', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Drum', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sensors', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Master Cylinder ', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vaccume Booster', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hnd Break', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Modulator', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Actuator', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pump', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Motor', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Master Cylinder ', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Upper Arm (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Upper Arm (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lower Arm (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lower Arm (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Stabilizer Link (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Stabilizer Link (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Hub Razor (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Hub Razor (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Hub Razor (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Hub Razor (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Shock Absorber (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Shock Absorber (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Shock Absorber (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Shock Absorber (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Shock Mount (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Shock Mount (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Shock Mount (R/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Shock Mount (L/H)', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rack', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tie Rod', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Power Steering', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Power Steering Fluid', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ball Joints', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Universal Joints', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bush & Mount', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Steering Knuckle', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Differential Oil', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Differential Oil Leak', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Differential Case', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Axle Shaft', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ring Gear (Crown Wheel)', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Differential Bearings', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 6, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Engine Wash', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Oil', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Oil Leak', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Head', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Block', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Piston', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Crankshaft', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Camshaft', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Valves', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sump', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pulley', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Belt', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 7, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Transmission Oil', 'category_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Transmission Oil Leak', 'category_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gear Box', 'category_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 8, 'created_at' => now(), 'updated_at' => now()],

            ['name' => '12V Battery Fluid', 'category_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '12V', 'category_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hybrid ', 'category_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 9, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Coolant', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Viper Water Tank', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Radiator', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Radiator Cap', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Radiator Fan', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Radiator Fan Belt', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Water Pump', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thermostat', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Overflow Tank', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hose', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sensors', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Air Filter', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 10, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Gas', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Compressor', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Condenser', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Accumulator', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Blower Fan', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Blower Fan Belt', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sensors', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hoses and Lines', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'A/C Control Unit', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'A/C Filter', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 11, 'created_at' => now(), 'updated_at' => now()],   

            ['name' => 'Head Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Head Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dim Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dim Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fog Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fog Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Parking Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Parking Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Parking Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Parking Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Signal Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Signal Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Signal Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Signal Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Fender Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Fender Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Brake Light (R/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Brake Light (L/H)', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Center Brake Light', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 12, 'created_at' => now(), 'updated_at' => now()], 

            ['name' => 'Horn', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Wiper Blades', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Wiper Blades', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Guard', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Inner Mud Guard (R/H)', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Front Inner Mud Guard (L/H)', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Inner Mud Guard (R/H)', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rear Inner Mud Guard (L/H)', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bonnet Lock', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dicky Lock', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Other', 'category_id' => 13, 'created_at' => now(), 'updated_at' => now()],            
        ]);

        DB::table('vehicles')->insert([
            ['reg_no' => 'ABC-1234', 'vehicle_category_id' => 1 , 'vehicle_type_id' => 1, 'make' => 'Toyota', 'model' => 'Corolla', 'year_of_manufacture' => 2018, 'fuel_type_id' => 1, 'transmission_id' => 2, 'ownership_type_id' => 1, 'company_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'XYZ-5678', 'vehicle_category_id' => 2 , 'vehicle_type_id' => 2, 'make' => 'Nissan', 'model' => 'Caravan', 'year_of_manufacture' => 2020, 'fuel_type_id' => 2, 'transmission_id' => 1, 'ownership_type_id' => 2, 'company_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'DEF-9012', 'vehicle_category_id' => 3 , 'vehicle_type_id' => 3, 'make' => 'Tata', 'model' => 'LP 410', 'year_of_manufacture' => 2016, 'fuel_type_id' => 2, 'transmission_id' => 1, 'ownership_type_id' => 3, 'company_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'GHI-3456', 'vehicle_category_id' => 4 , 'vehicle_type_id' => 4, 'make' => 'Hyundai', 'model' => 'Santa Fe', 'year_of_manufacture' => 2021, 'fuel_type_id' => 3, 'transmission_id' => 2, 'ownership_type_id' => 1, 'company_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'JKL-7890', 'vehicle_category_id' => 5 , 'vehicle_type_id' => 4, 'make' => 'Isuzu', 'model' => 'NQR 75', 'year_of_manufacture' => 2019, 'fuel_type_id' => 2, 'transmission_id' => 1, 'ownership_type_id' => 2, 'company_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'MNO-4321', 'vehicle_category_id' => 6 , 'vehicle_type_id' => 1, 'make' => 'Honda', 'model' => 'Civic', 'year_of_manufacture' => 2022, 'fuel_type_id' => 1, 'transmission_id' => 2, 'ownership_type_id' => 1, 'company_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'PQR-1122', 'vehicle_category_id' => 7 , 'vehicle_type_id' => 1, 'make' => 'Ford', 'model' => 'Focus', 'year_of_manufacture' => 2019, 'fuel_type_id' => 1, 'transmission_id' => 1, 'ownership_type_id' => 1, 'company_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'STU-3344', 'vehicle_category_id' => 8 , 'vehicle_type_id' => 2, 'make' => 'Chevrolet', 'model' => 'Express', 'year_of_manufacture' => 2020, 'fuel_type_id' => 2, 'transmission_id' => 1, 'ownership_type_id' => 2, 'company_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'VWX-5566', 'vehicle_category_id' => 9 , 'vehicle_type_id' => 3, 'make' => 'Mercedes', 'model' => 'Atego', 'year_of_manufacture' => 2021, 'fuel_type_id' => 2, 'transmission_id' => 2, 'ownership_type_id' => 3, 'company_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'YZA-7788', 'vehicle_category_id' => 10 , 'vehicle_type_id' => 4, 'make' => 'Volvo', 'model' => 'VNL', 'year_of_manufacture' => 2018, 'fuel_type_id' => 1, 'transmission_id' => 2, 'ownership_type_id' => 1, 'company_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'BCD-9900', 'vehicle_category_id' => 11 , 'vehicle_type_id' => 1, 'make' => 'BMW', 'model' => '320i', 'year_of_manufacture' => 2022, 'fuel_type_id' => 1, 'transmission_id' => 1, 'ownership_type_id' => 2, 'company_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'EFG-2233', 'vehicle_category_id' => 1 , 'vehicle_type_id' => 2, 'make' => 'Mazda', 'model' => 'CX-5', 'year_of_manufacture' => 2020, 'fuel_type_id' => 2, 'transmission_id' => 2, 'ownership_type_id' => 1, 'company_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'HIJ-4455', 'vehicle_category_id' => 1 , 'vehicle_type_id' => 3, 'make' => 'MAN', 'model' => 'TGX', 'year_of_manufacture' => 2017, 'fuel_type_id' => 2, 'transmission_id' => 1, 'ownership_type_id' => 3, 'company_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['reg_no' => 'KLM-6677', 'vehicle_category_id' => 5 , 'vehicle_type_id' => 4, 'make' => 'Ford', 'model' => 'F-150', 'year_of_manufacture' => 2022, 'fuel_type_id' => 1, 'transmission_id' => 2, 'ownership_type_id' => 2, 'company_id' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);

        DB::table('suppliers')->insert([
            ['name' => 'Dunston Auto traders','email' => 'sales@autotech.lk','phone' => '0771234567','address' => 'No. 45, Industrial Zone, Colombo 14','created_at' => now(),'updated_at' => now()],
            ['name' => 'Dai Lanka auto enterprises.','email' => 'info@globallube.com','phone' => '+94 112 345 678','address' => '123 Marine Drive, Galle','created_at' => now(),'updated_at' => now()],
            ['name' => 'Toyota Lanka (PVT) Ltd','email' => 'support@fleetparts.lk','phone' => '0719876543','address' => 'Warehouse Complex, Kandy Road, Kurunegala','created_at' => now(),'updated_at' => now()],
            ['name' => 'Shenal Wheel Alignment','email' => 'tools@quickfix.com','phone' => '+94 76 456 7890','address' => 'Tool Street, Matara','created_at' => now(),'updated_at' => now()],
            ['name' => 'United Motors Lanka PLC','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
            ['name' => 'Namal Auto Electricals','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
            ['name' => 'Ranga Auto Electricals','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
            ['name' => 'Vinuki Auto Traders','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
            ['name' => 'Snowline Enterprises','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
            ['name' => 'VSD Auto Mobiles','email' => 'orders@ecodrive.lk','phone' => '0751122334','address' => 'Battery Lane, Nugegoda','created_at' => now(),'updated_at' => now()],
        ]);

        DB::table('inventory_types')->insert([
            ['name' => 'Tools', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Engine Oil & Fluids', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Brake & Suspension Parts', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cleaning & Detailing', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Batteries & Electrical', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // DB::table('inventories')->insert([
        //     [
        //         'item_code' => '001',
        //         'name' => 'Torque Wrench',
        //         'description' => 'Adjustable torque wrench for engine and suspension work',
        //         'available_quantity' => 100,
        //         'remaining_quantity' => 100,
        //         'min_stock_level' => 20,
        //         'unit' => 'pcs',
        //         'purchase_date' => '2025-07-15',
        //         'supplier_id' => 1,
        //         'inventory_type_id' => 1, // Tools
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'item_code' => '002',
        //         'name' => 'Engine Oil SAE 10W-30',
        //         'description' => 'Synthetic engine oil for petrol vehicles',
        //         'available_quantity' => 200,
        //         'remaining_quantity' => 200,
        //         'min_stock_level' => 20,
        //         'unit' => 'liters',
        //         'purchase_date' => '2025-08-01',
        //         'supplier_id' => 2,
        //         'inventory_type_id' => 2, // Engine Oil & Fluids
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'item_code' => '003',
        //         'name' => 'Brake Pads - Front (Toyota Corolla)',
        //         'description' => 'OEM brake pads compatible with 2018–2021 Corolla models',
        //         'available_quantity' => 50,
        //         'remaining_quantity' => 50,
        //         'min_stock_level' => 15,
        //         'unit' => 'packs',
        //         'purchase_date' => '2025-07-28',
        //         'supplier_id' => 3,
        //         'inventory_type_id' => 3, // Brake & Suspension Parts
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'item_code' => '004',
        //         'name' => 'Degreaser Spray',
        //         'description' => 'Heavy-duty degreaser for engine bay and undercarriage cleaning',
        //         'available_quantity' => 30,
        //         'remaining_quantity' => 30,
        //         'min_stock_level' => 13,
        //         'unit' => 'boxes',
        //         'purchase_date' => '2025-08-10',
        //         'supplier_id' => 1,
        //         'inventory_type_id' => 4, // Cleaning & Detailing
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'item_code' => '005',
        //         'name' => '12V Battery (N70)',
        //         'description' => 'Lead-acid battery suitable for vans and SUVs',
        //         'available_quantity' => 150,
        //         'remaining_quantity' => 150,
        //         'min_stock_level' => 20,
        //         'unit' => 'pcs',
        //         'purchase_date' => '2025-08-05',
        //         'supplier_id' => 2,
        //         'inventory_type_id' => 5, // Batteries & Electrical
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        // ]);

        DB::table('category_supplier')->insert([
            ['defect_category_id' => 1, 'supplier_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 1, 'supplier_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 1, 'supplier_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 2, 'supplier_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 2, 'supplier_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 3, 'supplier_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 3, 'supplier_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 4, 'supplier_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 5, 'supplier_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 6, 'supplier_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 7, 'supplier_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 7, 'supplier_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['defect_category_id' => 7, 'supplier_id' => 7, 'created_at' => now(), 'updated_at' => now()],
        ]);

    }
}
